name: Build OpenWrt x86lean

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: x86lean.config
  TZ: Asia/Shanghai
  DEVICE: x86lean
  CCACHE_DIR: /workdir/openwrt/.ccache

jobs:
  build-openwrt:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 明确指定写入权限
      actions: write   # 确保 Action 可以运行

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 4
        delete_tags: true

    - name: Delete Old Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 1

    - name: Free Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get clean

    - name: Setup Environment
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo apt update && sudo apt install -y build-essential ccache git \
          libncurses5-dev libssl-dev python3 unzip wget
        sudo mkdir -p /workdir && sudo chown $USER:$GROUPS /workdir

    - name: Clone Repository
      run: |
        git clone $REPO_URL -b $REPO_BRANCH /workdir/openwrt

    - name: Cache ccache
      id: cache-ccache
      uses: actions/cache@v3
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ runner.os }}-openwrt-${{ env.DEVICE }}-ccache-${{ hashFiles(env.CONFIG_FILE) }}
        restore-keys: ${{ runner.os }}-openwrt-${{ env.DEVICE }}-

    - name: Configure OpenWrt
      run: |
        cd /workdir/openwrt
        cp $GITHUB_WORKSPACE/$CONFIG_FILE .config
        ./scripts/feeds update -a && ./scripts/feeds install -a
        sed -i 's/192.168.1.1/192.168.0.1/g' package/base-files/files/bin/config_generate
        make defconfig

    - name: Download and Build
      run: |
        cd /workdir/openwrt
        export CCACHE_DIR=$CCACHE_DIR
        make download -j$(nproc)
        if [ "${{ steps.cache-ccache.outputs.cache-hit }}" != "true" ]; then
          make -j$(nproc) || make -j1 V=s
        fi
        ccache -s

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DEVICE }}-${{ github.run_id }}
        path: /workdir/openwrt/bin/targets/x86/64/*.img.gz

    - name: Debug GITHUB_TOKEN
      run: |
        echo "GITHUB_TOKEN is set to: ${GITHUB_TOKEN:0:10}..."  # 打印前10个字符
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release Firmware
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.DEVICE }}-${{ github.run_id }}
        files: /workdir/openwrt/bin/targets/x86/64/*.img.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}