name: gdqax6600

on:
  schedule:
    - cron: '0 15 */15 * *' # 每 15 天的 15:00 执行一次
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: gdqax6600.config
  TZ: Asia/Shanghai
  DEVICE: gdqax6600
  UPLOAD_OUTPUT: true
  CCACHE_DIR: /workdir/openwrt/.ccache
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build-openwrt:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 删除旧的 Releases 保留最近4个
      uses: dev-drprasad/delete-older-releases@master
      with:
          keep_latest: 4
          delete_tags: true

    - name: 删除最近的workflow 保留最近1个
      uses: Mattraks/delete-workflow-runs@main
      with:
          retain_days: 0
          keep_minimum_runs: 1

    - name: 初始化构建环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
        genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
        libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
        libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf \
        python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
        swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: 克隆源码
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        sudo mkdir -p -m 777 /mnt/openwrt/{dl,feeds,staging_dir}
        ln -s /mnt/openwrt/dl /workdir/openwrt/dl
        ln -s /mnt/openwrt/feeds /workdir/openwrt/feeds
        ln -s /mnt/openwrt/staging_dir /workdir/openwrt/staging_dir

    - name: 配置 Feeds
      run: |
        cd openwrt
        rm -rf package/helloworld
        git clone --depth=1 https://github.com/fw876/helloworld.git package/helloworld
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 下载依赖
      run: |
        cp -f $GITHUB_WORKSPACE/gdqax6600.config $GITHUB_WORKSPACE/openwrt/.config
        cd openwrt
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译固件
      run: |
        cd openwrt
        export CCACHE_DIR=${{ env.CCACHE_DIR }}
        export CC="ccache gcc"
        export CXX="ccache g++"
        make -j$(nproc) V=s 2>&1 | tee $GITHUB_WORKSPACE/build.log
        ccache -s

    - name: 提交编译日志到仓库
      run: |
        cd $GITHUB_WORKSPACE
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add build.log
        git commit -m "上传编译日志 $(date +%Y-%m-%d_%H-%M)" || echo "No changes to commit"
        git push

    - name: 上传编译日志
      uses: actions/upload-artifact@v3
      with:
        name: build-log
        path: $GITHUB_WORKSPACE/build.log

    - name: 发布固件至 Release
      uses: ncipollo/release-action@v1
      with:
          tag: "${{ env.DEVICE }}-$(date +%Y-%m-%d_%H-%M)"
          artifacts: "openwrt/bin/targets/*/*/*"
