name: Build OpenWrt x86lean

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: x86lean.config
  TZ: Asia/Shanghai
  DEVICE: x86lean

jobs:
  build-openwrt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check Config File
      run: |
        ls -l $GITHUB_WORKSPACE/$CONFIG_FILE || echo "Config file not found!"

    - name: Clone Repository
      run: |
        rm -rf /workdir/openwrt
        git clone $REPO_URL -b $REPO_BRANCH /workdir/openwrt

    - name: Configure OpenWrt
      run: |
        cd /workdir/openwrt
        cp -f $GITHUB_WORKSPACE/$CONFIG_FILE .config
        ls -l .config
        cat .config | head -n 10  # 调试用，确认内容
        ./scripts/feeds update -a && ./scripts/feeds install -a
        sed -i 's/192.168.1.1/192.168.0.1/g' package/base-files/files/bin/config_generate
        make oldconfig

    # 后续步骤保持不变
    - name: Download and Build
      run: |
        cd /workdir/openwrt
        make download -j$(nproc)
        make -j$(nproc) || make -j1 V=s
